kind: ConfigMap
metadata:
  name: burrow-config
  namespace: kafka
apiVersion: v1
data:
  burrow.toml: |-
    [zookeeper]
    servers=[ "ke-cp-zookeeper-0.ke-cp-zookeeper-headless:2181", "ke-cp-zookeeper-1.ke-cp-zookeeper-headless:2181", "ke-cp-zookeeper-2.ke-cp-zookeeper-headless:2181" ]
    timeout=6
    root-path="/burrow"

    [cluster.local]
    class-name="kafka"
    servers=[ "ke-cp-kafka-headless:9092" ]
    topic-refresh=60
    offset-refresh=30

    [consumer.local]
    class-name="kafka"
    cluster="local"
    servers=[ "ke-cp-kafka-headless:9092" ]
    group-blacklist=""
    group-whitelist=""

    [consumer.local_zk]
    class-name="kafka_zk"
    cluster="local"
    servers=[ "ke-cp-zookeeper-0.ke-cp-zookeeper-headless:2181", "ke-cp-zookeeper-1.ke-cp-zookeeper-headless:2181", "ke-cp-zookeeper-2.ke-cp-zookeeper-headless:2181" ]
    zookeeper-path="/local"
    zookeeper-timeout=30
    group-blacklist=""
    group-whitelist=""

    [httpserver.default]
    address=":8000"
